### ISSUE TITLE
Issue 

### ISSUE THREAD

**Issue by K2binks** [KotatsuApp/Kotatsu#1101]
### Brief summary

J'arrive pas à installer l'application kotatsu, pourtant j'ai autorisé l'installation d'application inconnu 

### Steps to reproduce

![Screenshot_20240918-075212](https://github.com/user-attachments/assets/b27c8e0e-9c0b-4d8c-92f4-3a4158161c42)

java.lang.SecurityException: Can't install packages while in secure FRP
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2374)
	at android.os.Parcel.createException(Parcel.java:2358)
	at android.os.Parcel.readException(Parcel.java:2341)
	at android.os.Parcel.readException(Parcel.java:2283)
	at android.content.pm.IPackageInstallerSession$Stub$Proxy.commit(IPackageInstallerSession.java:673)
	at android.content.pm.PackageInstaller$Session.commit(PackageInstaller.java:1243)
	at x4.b.q(SourceFile:212)
	at x4.b.r(SourceFile:1)
	at x4.b.o(SourceFile:1)
	at x4.a.run(SourceFile:1)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.pm.PackageInstallerSession.markAsSealed(PackageInstallerSession.java:1382)
	at com.android.server.pm.PackageInstallerSession.commit(PackageInstallerSession.java:1126)
	at android.content.pm.IPackageInstallerSession$Stub.onTransact(IPackageInstallerSession.java:336)
	at android.os.Binder.execTransactInternal(Binder.java:1154)
	at android.os.Binder.execTransact(Binder.java:1123)

### Kotatsu version

7.5.2.

### Android version

11

### Device

realme C25Y

### Acknowledgements

- [X] This is not a duplicate of an existing issue. Please look through the list of [open issues](https://github.com/KotatsuApp/Kotatsu/issues) before creating a new one.
- [X] This is not an issue with a specific manga source. Otherwise, you have to open an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by ztimms73** [comment]
Device issue?

**Comment by Koitharu** [comment]
I guess this is not an application issue
