### ISSUE TITLE
Connection reset when loading manga

### ISSUE THREAD

**Issue by gingercookies** [KotatsuApp/Kotatsu#348]
### Brief summary

I have a pi-hole running as dns resolver for my network.
As i open kotatsu and choose a manga i want to read, the loading take about 8s (on 2mb/s internet connection) and then it stop, output "Connection reset" with this error:
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:191)
	at java.net.SocketInputStream.read(SocketInputStream.java:143)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:945)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:909)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:824)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:797)
	at okio.InputStreamSource.read(SourceFile:95)
	at okio.InputStreamSource.read(SourceFile:19)
	at okio.RealBufferedSource.request(SourceFile:31)
	at okio.RealBufferedSource.require(Unknown Source:0)
	at okhttp3.internal.http2.Http2Reader.nextFrame(SourceFile:10)
	at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(SourceFile:12)
	at okhttp3.internal.concurrent.TaskQueue$execute$1.runOnce(SourceFile:13)
	at okhttp3.internal.concurrent.TaskRunner.access$runTask(SourceFile:19)
	at okhttp3.internal.concurrent.TaskRunner$runnable$1.run(SourceFile:52)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

When i use my mobile connection which don't have pi-hole as dns resolver or using official mangadex website(with pi-hole on), it worked

### Steps to reproduce

1. Open Kotatsu
2. Open [this manga](https://mangadex.org/title/8c27bba8-eba6-440c-84e2-616651079e0e/my-awkward-girl-friend) and choose chapter 1
3. Waiting about 5-8s and got "Connection reset" error

### Kotatsu version

4.4.8

### Android version

12

### Device

Redmi Note 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Koitharu** [comment]
![изображение](https://user-images.githubusercontent.com/8948226/233784853-57e3bef0-25bf-4a05-8a9d-5d70ecfa6f67.png)

Unfortunately I have the same issue even via curl, cannot figure out what can be a reason of it

**Comment by Koitharu** [comment]
Even in browser...
![изображение](https://user-images.githubusercontent.com/8948226/233787322-5654d17d-174e-401f-9566-d7c2c86eef26.png)

**Comment by Koitharu** [comment]
Feel free to reopen if you have any further information, however now it looks like no way to fix this since it`s a server issue
