### ISSUE TITLE
Network error

### ISSUE THREAD

**Issue by GladRedFox719** [KotatsuApp/Kotatsu#371]
### Brief summary

Can't download or read the manga.

### Steps to reproduce

java.net.UnknownHostException: Unable to resolve host "pic5.taadd.com": No address associated with hostname
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:124)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
	at java.net.InetAddress.getAllByName(InetAddress.java:1152)
	at h9.d.e(SourceFile:10)
	at v6.o.b(SourceFile:174)
	at v6.f.a(SourceFile:185)
	at v6.a.f(SourceFile:58)
	at w6.e.b(SourceFile:149)
	at t6.b.f(SourceFile:1030)
	at w6.e.b(SourceFile:149)
	at bc.c.f(SourceFile:735)
	at w6.e.b(SourceFile:149)
	at w6.f.f(SourceFile:146)
	at w6.e.b(SourceFile:149)
	at h9.f.f(SourceFile:5)
	at w6.e.b(SourceFile:149)
	at h9.a.f(SourceFile:130)
	at w6.e.b(SourceFile:149)
	at h9.b.b(Unknown Source:2)
	at ib.y3.f(SourceFile:100)
	at k9.l.f(SourceFile:9)
	at h9.c.f(SourceFile:286)
	at w6.e.b(SourceFile:149)
	at h9.a.f(SourceFile:111)
	at w6.e.b(SourceFile:149)
	at v6.j.h(SourceFile:94)
	at v6.g.run(SourceFile:38)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

### Kotatsu version

5.0.2

### Android version

13.0

### Device

Galaxy A23

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by ztimms73** [comment]
Logs ≠ steps to reproduce

**Comment by Koitharu** [comment]
This server "pic5.taadd.com" isn't accessible via web browser. Can you please provide a link to the manga with this issue?

**Comment by GladRedFox719** [comment]
My Wife Is From A Thousand Years Ago
 
https://www.ninemanga.com/manga/My+Wife+Is+From+a+Thousand+Years+Ago.html

**Comment by GladRedFox719** [comment]
My Wife Is From A Thousand Years Ago
 
https://www.ninemanga.com/manga/My+Wife+Is+From+a+Thousand+Years+Ago.html
