### ISSUE TITLE
Bug in download source 

### ISSUE THREAD

**Issue by Stu75e** [KotatsuApp/Kotatsu#398]
## Device information
* Kotatsu version: 5.2.3
* Android version: 11
* Device: a20

## Steps to reproduce
1. First step
2. Second step

## Issue
Bug in downloading manga

## Other details
Additional details and attachments.

javax.net.ssl.SSLHandshakeException: connection closed
	at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:362)
	at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:240)
	at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:217)
	at okhttp3.internal.connection.RealConnection.establishProtocol(SourceFile:93)
	at okhttp3.internal.connection.RealConnection.connect(SourceFile:132)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(SourceFile:254)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(SourceFile:56)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
	at okhttp3.internal.cache.CacheInterceptor.intercept(SourceFile:1013)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
	at okhttp3.internal.http.BridgeInterceptor.intercept(SourceFile:453)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(SourceFile:144)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
	at org.koitharu.kotatsu.core.network.MirrorSwitchInterceptor.intercept(SourceFile:23)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
	at org.koitharu.kotatsu.core.network.CommonHeadersInterceptor$ProxyChain.proceed(Unknown Source:2)
	at org.koitharu.kotatsu.core.parser.RemoteMangaRepository.intercept(SourceFile:18)
	at org.koitharu.kotatsu.core.network.CommonHeadersInterceptor.intercept(SourceFile:266)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
	at org.koitharu.kotatsu.core.network.GZipInterceptor.intercept(SourceFile:107)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
	at org.koitharu.kotatsu.core.network.GZipInterceptor.intercept(SourceFile:86)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(SourceFile:94)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(SourceFile:36)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.io.EOFException: connection closed
	... 28 more

**Comment by Oneloutre** [comment]
I don't think that it's a client-side bug, a ssl-handshake fail often happens when a website reboots (it's a common cloudflare issue) so I don't think it's such a big deal.
I think this issue could be closed.

Plus, with what website did the issue appeared ? you didn't mention it :/ we can help you but we don't really love quizzes X)

**Comment by Koitharu** [comment]
You can try to enable "Ignore SSL errors" option in settings
