### ISSUE TITLE
Image format not supported

### ISSUE THREAD

**Issue by SerpentStrike** [KotatsuApp/Kotatsu#464]
### Brief summary

Downloaded manga chapters on my tablet and opening one chapter shows 'Image format not supported'.

I also deleted the downloaded manga chapter and loaded that same chapter and has the same issue.

I pressed on 'Details' to check on browser and it loads fine (the downloaded manga did not allow me to check as pressing the 'open manga in a web browser' did nothing).

This occurs on few chapters (like 5/66 chapters go through this problem) of the manga and a few other mangas I've recently downloaded. Here is an example [page](https://img.manga18h.com/is-there-an-empty-room/chapter-63/001.jpg).

Tablet is on **Android 7** and it cannot be upgraded.

I also did a test on my phone Samsung S10e, **Android 12** and the images load fine on the chapters that I have a problems on the tablet. 

I also have a copy of the error report below:

java.io.IOException: Image format not supported
	at android.graphics.BitmapRegionDecoder.nativeNewInstance(Native Method)
	at android.graphics.BitmapRegionDecoder.newInstance(BitmapRegionDecoder.java:124)
	at android.graphics.BitmapRegionDecoder.newInstance(BitmapRegionDecoder.java:150)
	at com.davemorrissey.labs.subscaleview.decoder.UtilKt.BitmapRegionDecoder(SourceFile:3)
	at com.davemorrissey.labs.subscaleview.decoder.SkiaPooledImageRegionDecoder.initialiseDecoder(SourceFile:245)
	at com.davemorrissey.labs.subscaleview.decoder.SkiaPooledImageRegionDecoder.init(SourceFile:5)
	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$initTiles$1$1.invoke(SourceFile:3)
	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$initTiles$1$1.invoke(SourceFile:1)
	at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(SourceFile:57)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:116)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:94)
	Suppressed: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.Bitmap.recycle()' on a null object reference
		at org.koitharu.kotatsu.core.util.ext.FileKt$computeSize$2.invoke$4(SourceFile:66)
		at org.koitharu.kotatsu.core.util.ext.FileKt$computeSize$2.invoke(SourceFile:9)
		... 4 more

### Kotatsu version

5.3.10

### Android version

Android 7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If this is an issue with a parser, I should be opening an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by SerpentStrike** [comment]
I have also tried alternative providers and they provide the same result on my tablet.
