### ISSUE TITLE
Tracker tries to check for manga new chapters infinitely, until app force stopped

### ISSUE THREAD

**Issue by pepmak** [KotatsuApp/Kotatsu#489]
### Brief summary

In title.
My only sources are Comick and Mangadex.
Below are app's logs.

`
2023-09-08 22:00: doWork(): attempt 0
2023-09-08 22:00: Total 26 tracks
2023-09-08 22:00: Result: success: 26, failed: 0, retry: 0
2023-09-09 01:29: doWork(): attempt 0
2023-09-09 01:29: Total 26 tracks
2023-09-09 01:29: Result: success: 26, failed: 0, retry: 0
2023-09-09 12:39: doWork(): attempt 0
2023-09-09 12:39: Total 26 tracks
2023-09-09 12:39: E!fatal kotlinx.coroutines.JobCancellationException: Job was cancelled; job=JobImpl{Cancelling}@656e4

2023-09-09 12:39: doWork(): attempt 1
2023-09-09 12:39: Total 26 tracks
2023-09-09 12:39: E!fatal kotlinx.coroutines.JobCancellationException: Job was cancelled; job=JobImpl{Cancelling}@a1f4114

2023-09-09 12:39: doWork(): attempt 2
2023-09-09 12:39: Total 26 tracks
2023-09-09 12:39: E!fatal kotlinx.coroutines.JobCancellationException: Job was cancelled; job=JobImpl{Cancelling}@ab3d7e5

2023-09-09 12:39: doWork(): attempt 3
2023-09-09 12:39: Total 26 tracks
2023-09-09 12:39: E!fatal kotlinx.coroutines.JobCancellationException: Job was cancelled; job=JobImpl{Cancelling}@7cf2cc5

2023-09-09 12:39: doWork(): attempt 4
2023-09-09 12:39: Total 26 tracks
2023-09-09 12:39: E!fatal kotlinx.coroutines.JobCancellationException: Job was cancelled; job=JobImpl{Cancelling}@be17e72

2023-09-09 12:39: doWork(): attempt 5
2023-09-09 12:39: Total 26 tracks
2023-09-09 12:39: E!fatal kotlinx.coroutines.JobCancellationException: Job was cancelled; job=JobImpl{Cancelling}@b58f70f

2023-09-09 12:39: doWork(): attempt 6
2023-09-09 12:39: Total 26 tracks
2023-09-09 12:39: E!fatal kotlinx.coroutines.JobCancellationException: Job was cancelled; job=JobImpl{Cancelling}@403dea3

2023-09-09 12:39: doWork(): attempt 7
2023-09-09 12:39: Total 26 tracks
2023-09-09 12:39: E!fatal kotlinx.coroutines.JobCancellationException: Job was cancelled; job=JobImpl{Cancelling}@ba5b6d0

2023-09-09 12:39: doWork(): attempt 8
2023-09-09 12:39: Total 26 tracks
2023-09-09 12:39: E!fatal kotlinx.coroutines.JobCancellationException: Job was cancelled; job=JobImpl{Cancelling}@df22bdf

--- snip ---
--- snip ---
--- snip ---

2023-09-09 12:40: doWork(): attempt 383
2023-09-09 12:40: Total 26 tracks
2023-09-09 12:40: E!fatal kotlinx.coroutines.JobCancellationException: Job was cancelled; job=JobImpl{Cancelling}@a0be44f

2023-09-09 12:40: doWork(): attempt 384
2023-09-09 12:40: E!fatal kotlinx.coroutines.JobCancellationException: Job was cancelled; job=JobImpl{Cancelling}@c77636a

2023-09-09 12:40: doWork(): attempt 385
2023-09-09 12:40: Total 26 tracks
2023-09-09 12:40: E!fatal kotlinx.coroutines.JobCancellationException: Job was cancelled; job=JobImpl{Cancelling}@de5f80f

2023-09-09 12:40: doWork(): attempt 386
2023-09-09 12:40: Total 26 tracks
2023-09-09 12:40: E!fatal kotlinx.coroutines.JobCancellationException: Job was cancelled; job=JobImpl{Cancelling}@6089f01

2023-09-09 12:40: doWork(): attempt 388
2023-09-09 12:40: Total 26 tracks
2023-09-09 12:40: E!checkUpdatesAsync okhttp3.internal.http2.StreamResetException: stream was reset: REFUSED_STREAM
	at okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(SourceFile:201)
	at okhttp3.internal.connection.Exchange.readResponseHeaders(SourceFile:3)
	at okhttp3.internal.http.CallServerInterceptor.intercept(SourceFile:224)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
	at org.koitharu.kotatsu.core.network.CacheLimitInterceptor.intercept(SourceFile:5)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(SourceFile:94)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
	at okhttp3.internal.cache.CacheInterceptor.intercept(SourceFile:1010)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
	at okhttp3.internal.http.BridgeInterceptor.intercept(SourceFile:231)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(SourceFile:144)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
	at org.koitharu.kotatsu.core.network.MirrorSwitchInterceptor.intercept(SourceFile:23)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
	at org.koitharu.kotatsu.core.network.CommonHeadersInterceptor$ProxyChain.proceed(Unknown Source:2)
	at org.koitharu.kotatsu.core.parser.RemoteMangaRepository.intercept(SourceFile:18)
	at org.koitharu.kotatsu.core.network.CommonHeadersInterceptor.intercept(SourceFile:219)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
	at okhttp3.internal.http.BridgeInterceptor.intercept(SourceFile:336)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
	at org.koitharu.kotatsu.core.network.GZipInterceptor.intercept(SourceFile:107)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
	at org.koitharu.kotatsu.core.network.GZipInterceptor.intercept(SourceFile:86)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(SourceFile:94)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(SourceFile:36)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: okhttp3.internal.http2.StreamResetException: stream was reset: ENHANCE_YOUR_CALM
		... 31 more

2023-09-09 12:40: E!checkUpdatesAsync okhttp3.internal.http2.StreamResetException: stream was reset: ENHANCE_YOUR_CALM
	at okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(SourceFile:201)
	at okhttp3.internal.connection.Exchange.readResponseHeaders(SourceFile:3)
	at okhttp3.internal.http.CallServerInterceptor.intercept(SourceFile:224)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
	at org.koitharu.kotatsu.core.network.CacheLimitInterceptor.intercept(SourceFile:5)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(SourceFile:94)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
	at okhttp3.internal.cache.CacheInterceptor.intercept(SourceFile:1010)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
	at okhttp3.internal.http.BridgeInterceptor.intercept(SourceFile:231)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(SourceFile:144)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
	at org.koitharu.kotatsu.core.network.MirrorSwitchInterceptor.intercept(SourceFile:23)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
	at org.koitharu.kotatsu.core.network.CommonHeadersInterceptor$ProxyChain.proceed(Unknown Source:2)
	at org.koitharu.kotatsu.core.parser.RemoteMangaRepository.intercept(SourceFile:18)
	at org.koitharu.kotatsu.core.network.CommonHeadersInterceptor.intercept(SourceFile:219)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
	at okhttp3.internal.http.BridgeInterceptor.intercept(SourceFile:336)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
	at org.koitharu.kotatsu.core.network.GZipInterceptor.intercept(SourceFile:107)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
	at org.koitharu.kotatsu.core.network.GZipInterceptor.intercept(SourceFile:86)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(SourceFile:94)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(SourceFile:36)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: okhttp3.internal.http2.StreamResetException: stream was reset: REFUSED_STREAM
		... 31 more
	Suppressed: okhttp3.internal.http2.StreamResetException: stream was reset: ENHANCE_YOUR_CALM
		... 31 more
		Suppressed: okhttp3.internal.http2.StreamResetException: stream was reset: ENHANCE_YOUR_CALM
			... 31 more

2023-09-09 12:40: E!checkUpdatesAsync okhttp3.internal.http2.StreamResetException: stream was reset: ENHANCE_YOUR_CALM
	at okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(SourceFile:201)
	at okhttp3.internal.connection.Exchange.readResponseHeaders(SourceFile:3)
	at okhttp3.internal.http.CallServerInterceptor.intercept(SourceFile:224)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
	at org.koitharu.kotatsu.core.network.CacheLimitInterceptor.intercept(SourceFile:5)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(SourceFile:94)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
	at okhttp3.internal.cache.CacheInterceptor.intercept(SourceFile:1010)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
	at okhttp3.internal.http.BridgeInterceptor.intercept(SourceFile:231)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(SourceFile:144)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
	at org.koitharu.kotatsu.core.network.MirrorSwitchInterceptor.intercept(SourceFile:23)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
	at org.koitharu.kotatsu.core.network.CommonHeadersInterceptor$ProxyChain.proceed(Unknown Source:2)
	at org.koitharu.kotatsu.core.parser.RemoteMangaRepository.intercept(SourceFile:18)
	at org.koitharu.kotatsu.core.network.CommonHeadersInterceptor.intercept(SourceFile:219)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
	at okhttp3.internal.http.BridgeInterceptor.intercept(SourceFile:336)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
	at org.koitharu.kotatsu.core.network.GZipInterceptor.intercept(SourceFile:107)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
	at org.koitharu.kotatsu.core.network.GZipInterceptor.intercept(SourceFile:86)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(SourceFile:94)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(SourceFile:36)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: okhttp3.internal.http2.StreamResetException: stream was reset: ENHANCE_YOUR_CALM
		... 31 more
	Suppressed: okhttp3.internal.http2.StreamResetException: stream was reset: ENHANCE_YOUR_CALM
		... 31 more
		Suppressed: okhttp3.internal.http2.StreamResetException: stream was reset: ENHANCE_YOUR_CALM
			... 31 more

2023-09-09 12:40: Result: success: 23, failed: 3, retry: 0
`

### Kotatsu version

6.0.2 (F-droid)

### Android version

12.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If this is an issue with a parser, I should be opening an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by pepmak** [comment]
Didn't have this issue anymore.
