### ISSUE TITLE
[Bug]  mangadex

### ISSUE THREAD

**Issue by Stu75e** [KotatsuApp/Kotatsu#536]
## Device information
* Kotatsu version: 6.2.2
* Android version: 11
* Device: a20

## Steps to reproduce
1. First step
2. Second step

## Issue

```
javax.net.ssl.SSLProtocolException: Read error: ssl=0x77290d7b08: Failure in SSL library, usually a protocol error
error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT (external/boringssl/src/crypto/fipsmodule/cipher/e_aes.c:1044 0x771befa05a:0x00000000)
error:1000008b:SSL routines:OPENSSL_internal:DECRYPTION_FAILED_OR_BAD_RECORD_MAC (external/boringssl/src/ssl/tls_record.cc:298 0x771befa05a:0x00000000)
	at com.android.org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
	at com.android.org.conscrypt.NativeSsl.readDirectByteBuffer(NativeSsl.java:568)
	at com.android.org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1095)
	at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1079)
	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:876)
	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:747)
	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:712)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:849)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:815)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:788)
	at okio.InputStreamSource.read(SourceFile:95)
	at okio.InputStreamSource.read(SourceFile:19)
	at okio.RealBufferedSource.request(SourceFile:31)
	at okio.RealBufferedSource.require(SourceFile:1)
	at okhttp3.internal.http2.Http2Reader.nextFrame(SourceFile:10)
	at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(SourceFile:12)
	at okhttp3.internal.concurrent.TaskQueue$execute$1.runOnce(SourceFile:13)
	at okhttp3.internal.concurrent.TaskRunner.access$runTask(SourceFile:19)
	at okhttp3.internal.concurrent.TaskRunner$runnable$1.run(SourceFile:52)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)


## Other details
Additional details and attachments.

**Comment by ztimms73** [comment]
Source issues must be created [here](https://github.com/KotatsuApp/kotatsu-parsers)
