### ISSUE TITLE
Crash at app startup

### ISSUE THREAD

**Issue by Dusky-dev** [KotatsuApp/Kotatsu#806]
### Brief summary

FATAL EXCEPTION: Thread-14
Process: org.koitharu.kotatsu, PID: 13711
java.lang.IllegalArgumentException: Tried to schedule job for non-existent component: ComponentInfo{org.koitharu.kotatsu/org.acra.sender.JobSenderService}
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3032)
	at android.os.Parcel.createException(Parcel.java:3012)
	at android.os.Parcel.readException(Parcel.java:2995)
	at android.os.Parcel.readException(Parcel.java:2937)
	at android.app.job.IJobScheduler$Stub$Proxy.schedule(IJobScheduler.java:263)
	at android.app.JobSchedulerImpl.schedule(JobSchedulerImpl.java:50)
	at androidx.cardview.widget.CardView$1.scheduleReports(SourceFile:509)
	at androidx.work.impl.Processor$$ExternalSyntheticLambda2.run(SourceFile:285)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.job.JobSchedulerService$JobSchedulerStub.enforceValidJobRequest(JobSchedulerService.java:3022)
	at com.android.server.job.JobSchedulerService$JobSchedulerStub.schedule(JobSchedulerService.java:3077)
	at android.app.job.IJobScheduler$Stub.onTransact(IJobScheduler.java:153)
	at android.os.Binder.execTransactInternal(Binder.java:1283)
	at android.os.Binder.execTransact(Binder.java:1227)

### Kotatsu version

6.7.3

### Android version

13.0

### Device

Xiaomi 12 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If this is an issue with a parser, I should be opening an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by Dusky-dev** [comment]
Upgraded to 6.7.4, issue still present.

**Comment by Dusky-dev** [comment]
So I updated to 6.7.5 and that seemed to fix it so I'm closing this issue
