### ISSUE TITLE
Application not responding

### ISSUE THREAD

**Issue by lhjgege** [KotatsuApp/Kotatsu#828]
### Brief summary

If there is only one cartoon in the Favorites or History interface, clicking on the cartoon will cause the application to become unresponsive.

### Steps to reproduce

https://github.com/KotatsuApp/Kotatsu/assets/20966610/ce37bded-d51d-42f4-af68-84bfa50bb64b

### Kotatsu version

6.8

### Android version

android 14

### Device

xiaomi 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If this is an issue with a parser, I should be opening an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by lhjgege** [comment]
----- dumping pid: 27428 at 338810671

----- pid 27428 at 2024-03-21 19:30:48.327491792+0800 -----
Cmd line: org.koitharu.kotatsu
Build fingerprint: 'Xiaomi/fuxi/fuxi:14/UKQ1.230804.001/V816.0.7.0.UMCCNXM:user/release-keys'
ABI: 'arm64'
Build type: optimized
suspend all histogram:	Sum: 119us 99% C.I. 0.106us-56us Avg: 9.916us Max: 56us
DALVIK THREADS (51):
"main" prio=5 tid=1 Blocked
  | group="main" sCount=1 ucsCount=0 flags=1 obj=0x730374c8 self=0xb400007cd3d9ac00
  | sysTid=27428 nice=-10 cgrp=top-app sched=0/0 handle=0x7cd53d94f8
  | state=S schedstat=( 334453305 6598753 873 ) utm=24 stm=9 core=7 HZ=100
  | stack=0x7fdc72f000-0x7fdc731000 stackSize=8188KB
  | held mutexes=
  at org.koitharu.kotatsu.core.parser.MangaRepository$Factory.create(SourceFile:29)
  - waiting to lock <0x0978e59a> (a java.util.EnumMap) held by thread 35
  at org.koitharu.kotatsu.details.domain.RelatedMangaUseCase.invoke(SourceFile:61)
  at org.koitharu.kotatsu.details.ui.DetailsViewModel$relatedManga$1.invokeSuspend(SourceFile:58)
  at org.koitharu.kotatsu.details.ui.DetailsViewModel$relatedManga$1.invoke(SourceFile:13)
  at kotlinx.coroutines.flow.FlowKt__ZipKt$combine$1$1.invokeSuspend(SourceFile:216)
  at kotlinx.coroutines.flow.FlowKt__ZipKt$combine$1$1.invoke(SourceFile:35)
  at kotlinx.coroutines.flow.FlowKt__ZipKt$combine$1$1.invoke(SourceFile:22)
  at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invokeSuspend(SourceFile:35)
  at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invoke(SourceFile:13)
  at kotlinx.coroutines.AbstractCoroutine.start(SourceFile:26)
  at kotlin.TuplesKt.launch(SourceFile:20)
  at kotlin.TuplesKt.launch$default(SourceFile:12)
  at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1.emit(SourceFile:105)
  at kotlinx.coroutines.flow.StateFlowImpl.collect(SourceFile:173)
  at kotlinx.coroutines.flow.ReadonlyStateFlow.collect(unavailable:2)
  at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3.invokeSuspend(SourceFile:47)
  at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3.invoke(SourceFile:13)
  at okio.Okio.startUndispatchedOrReturn(SourceFile:16)
  at kotlin.TuplesKt.coroutineScope(SourceFile:10)
  at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest.flowCollect(SourceFile:7)
  at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo(SourceFile:6)
  at kotlinx.coroutines.flow.internal.ChannelFlow$collectToFun$1.invokeSuspend(SourceFile:33)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
  at kotlinx.coroutines.DispatchedTask.run(SourceFile:115)
  at kotlinx.coroutines.EventLoopImplPlatform.processUnconfinedEvent(SourceFile:24)
  at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(SourceFile:79)
  at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(SourceFile:33)
  at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(SourceFile:17)
  at kotlinx.coroutines.flow.SharedFlowImpl.tryEmit(SourceFile:30)
  at kotlinx.coroutines.flow.internal.SubscriptionCountStateFlow.increment(SourceFile:44)
  - locked <0x0d8adecb> (a kotlinx.coroutines.flow.internal.SubscriptionCountStateFlow)
  at kotlinx.coroutines.flow.internal.AbstractSharedFlow.allocateSlot(SourceFile:71)
  at kotlinx.coroutines.flow.StateFlowImpl.collect(SourceFile:101)
  at kotlinx.coroutines.flow.ReadonlyStateFlow.collect(unavailable:2)
  at org.koitharu.kotatsu.core.util.ext.FlowObserverKt$observe$1.invokeSuspend(SourceFile:31)
  at org.koitharu.kotatsu.core.util.ext.FlowObserverKt$observe$1.invoke(SourceFile:13)
  at kotlinx.coroutines.AbstractCoroutine.start(SourceFile:26)
  at kotlin.TuplesKt.launch(SourceFile:20)
  at kotlin.TuplesKt.launch$default(SourceFile:12)
  at kotlin.ResultKt.observe(SourceFile:19)
  at org.koitharu.kotatsu.details.ui.DetailsFragment.onViewBindingCreated(SourceFile:282)
  at org.koitharu.kotatsu.core.ui.BaseFragment.onViewCreated(SourceFile:21)
  at androidx.fragment.app.Fragment.performViewCreated(SourceFile:15)
  at androidx.fragment.app.FragmentStateManager.createView(SourceFile:271)
  at androidx.fragment.app.FragmentStateManager.moveToExpectedState(SourceFile:201)
  at androidx.fragment.app.FragmentManager.moveToState(SourceFile:58)
  at androidx.fragment.app.FragmentManager.dispatchStateChange(SourceFile:34)
  at androidx.fragment.app.FragmentActivity.onStart(SourceFile:35)
  at androidx.appcompat.app.AppCompatActivity.onStart(SourceFile:1)
  at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1594)
  at android.app.Activity.performStart(Activity.java:8931)
  at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4016)
  at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:235)
  at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:215)
  at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:187)
  at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:101)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2589)
  at android.os.Handler.dispatchMessage(Handler.java:106)
  at android.os.Looper.loopOnce(Looper.java:224)
  at android.os.Looper.loop(Looper.java:318)
  at android.app.ActivityThread.main(ActivityThread.java:8759)
  at java.lang.reflect.Method.invoke(Native method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

**Comment by Koitharu** [comment]
Thanks a lot for the log
