### ISSUE TITLE
Crash: IndexOutOfBoundsException in FragmentManager on A14

### ISSUE THREAD

**Issue by Koitharu** [KotatsuApp/Kotatsu#923]
### Brief summary

```
java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.util.Objects.checkIndex(Objects.java:359)
	at java.util.ArrayList.get(ArrayList.java:434)
	at androidx.fragment.app.FragmentManager.prepareBackStackState(FragmentManager.java:2491)
	at androidx.fragment.app.FragmentManager$PrepareBackStackTransitionState.generateOps(FragmentManager.java:3739)
	at androidx.fragment.app.FragmentManager.generateOpsForPendingActions(FragmentManager.java:2271)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1938)
	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:661)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```

https://bugs.kotatsu.app/app/1/bug/10579/report

Need help with reproducing and fixing

### Steps to reproduce

Unknown, probably in settings while popBackStack

### Kotatsu version

7.x

### Android version

14

### Device

Multiple

### Acknowledgements

- [X] This is not a duplicate of an existing issue. Please look through the list of [open issues](https://github.com/KotatsuApp/Kotatsu/issues) before creating a new one.
- [X] This is not an issue with a specific manga source. Otherwise, you have to open an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by BasetEsmaeili** [comment]
I have the same issue. Does anyone have a solution to fix this?

**Comment by Koitharu** [comment]
@BasetEsmaeili could you please provide step-to-reproduce or screen recording as well?

**Comment by Koitharu** [comment]
Looks like finally it was fixed
https://developer.android.com/jetpack/androidx/releases/fragment#1.8.3

**Comment by BasetEsmaeili** [comment]
> Looks like finally it was fixed https://developer.android.com/jetpack/androidx/releases/fragment#1.8.3

I've never been able to reproduce it.
It just appears on crash report services with a significant figure.
I think it's a background crash that the user can't see because nobody reported it.
Thanks for posting the changelog link. I will test it.

**Comment by Koitharu** [comment]
I guess this is not a background crash, it happens in settings activity on some devices only (mostly Samsung and some Pixel models)
