### ISSUE TITLE
Found Fatal Exception Crashes from Testing

### ISSUE THREAD

**Issue by Mai-hh** [KotatsuApp/Kotatsu#982]
### Brief summary

Hi! I'm a student researcher currently working on a project in the area of Android app analysis. As a part of the work centered around Intents, I found a bug that resulted in crashes after analyzing logs/execution traces. Below are the relevant activities, traces, and adb commands that triggered the crashes.

These bugs may be hidden in unexposed Activities, but they are worth investigating into to prevent potential issues down the line and addressing to improve the overall robustness and quality. If anyone can be confirm these to be valid bugs first, I would appreciate it, and I can help provide more information as needed.

### Steps to reproduce

adb command that triggers it:
```
#!/bin/bash

adb shell su 0 am start -n "org.koitharu.kotatsu/org.koitharu.kotatsu.browser.cloudflare.CloudFlareActivity" 
echo adb shell su 0 am start -n "org.koitharu.kotatsu/org.koitharu.kotatsu.browser.cloudflare.CloudFlareActivity" 
sleep 3.0
adb shell am force-stop org.koitharu.kotatsu
sleep 2.0
adb shell su 0 am start -n "org.koitharu.kotatsu/org.koitharu.kotatsu.browser.cloudflare.CloudFlareActivity"  -d "!0!"
sleep 3.0
adb shell am force-stop org.koitharu.kotatsu
sleep 2.0
```

## org.koitharu.kotatsu/org.koitharu.kotatsu.browser.cloudflare.CloudFlareActivity
Execution trace:
```
--------- beginning of crash
07-23 00:15:41.391 19023 19023 E AndroidRuntime: FATAL EXCEPTION: main
07-23 00:15:41.391 19023 19023 E AndroidRuntime: Process: org.koitharu.kotatsu, PID: 19023
07-23 00:15:41.391 19023 19023 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.koitharu.kotatsu/org.koitharu.kotatsu.browser.cloudflare.CloudFlareActivity}: java.lang.IllegalArgumentException: Expected URL scheme 'http' or 'https' but no scheme was found for 
07-23 00:15:41.391 19023 19023 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3645)
07-23 00:15:41.391 19023 19023 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
07-23 00:15:41.391 19023 19023 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
07-23 00:15:41.391 19023 19023 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
07-23 00:15:41.391 19023 19023 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
07-23 00:15:41.391 19023 19023 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
07-23 00:15:41.391 19023 19023 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
07-23 00:15:41.391 19023 19023 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
07-23 00:15:41.391 19023 19023 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
07-23 00:15:41.391 19023 19023 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7872)
07-23 00:15:41.391 19023 19023 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-23 00:15:41.391 19023 19023 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
07-23 00:15:41.391 19023 19023 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
07-23 00:15:41.391 19023 19023 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Expected URL scheme 'http' or 'https' but no scheme was found for 
07-23 00:15:41.391 19023 19023 E AndroidRuntime: 	at okhttp3.HttpUrl$Builder.parse$okhttp(SourceFile:979)
07-23 00:15:41.391 19023 19023 E AndroidRuntime: 	at org.koitharu.kotatsu.browser.cloudflare.CloudFlareClient.getClearance(SourceFile:9)
07-23 00:15:41.391 19023 19023 E AndroidRuntime: 	at org.koitharu.kotatsu.browser.cloudflare.CloudFlareClient.<init>(SourceFile:10)
07-23 00:15:41.391 19023 19023 E AndroidRuntime: 	at org.koitharu.kotatsu.browser.cloudflare.CloudFlareActivity.onCreate(SourceFile:57)
07-23 00:15:41.391 19023 19023 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8305)
07-23 00:15:41.391 19023 19023 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8284)
07-23 00:15:41.391 19023 19023 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
07-23 00:15:41.391 19023 19023 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3626)
07-23 00:15:41.391 19023 19023 E AndroidRuntime: 	... 12 more
```

### Kotatsu version

7.3

### Android version

13.0

### Device

Android Studio Emulator

### Acknowledgements

- [X] This is not a duplicate of an existing issue. Please look through the list of [open issues](https://github.com/KotatsuApp/Kotatsu/issues) before creating a new one.
- [X] This is not an issue with a specific manga source. Otherwise, you have to open an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by Koitharu** [comment]
Thanks
